#!/usr/bin/env bash
# This set is based on the first set of VSM models, CV train sets

#All Topic Modelling based prediction models
screen -dmS eval.CvLda4TopicModel bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_TOPICMODEL.py '/u01/bigdata/02d_d2vModel1/features/eval_CvLda4TopicModel.eval' '/u01/bigdata/02d_d2vModel1/CvLda4PreProcTopicModel.model' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/TOPIC_NONE' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.CvLda5TopicModel bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_TOPICMODEL.py '/u01/bigdata/02d_d2vModel1/features/eval_CvLda5TopicModel.eval' '/u01/bigdata/02d_d2vModel1/CvLda5PreProcTopicModel.model' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/TOPIC_NONE' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"

#All Similarity based prediction models (Based on W2V vectors)
screen -dmS eval.appD2vTrainW2v100min1.SIM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_SIMILARITYMODEL.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min1.SIM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/SIM_W2V100min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min1.SIM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_SIMILARITYMODEL.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min1.SIM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/SIM_W2V300min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v100min2.SIM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_SIMILARITYMODEL.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min2.SIM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/SIM_W2V100min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min2.SIM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_SIMILARITYMODEL.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min2.SIM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/SIM_W2V300min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
#All Similarity based prediction models (Based on D2V vectors)
screen -dmS eval.appD2vTrainD2v100.SIM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_SIMILARITYMODEL.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v100.SIM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v100Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v100Preproc.features' '/u01/bigdata/02d_d2vModel1/features/SIM_D2V100' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainD2v300.SIM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_SIMILARITYMODEL.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v300.SIM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v300Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v300Preproc.features' '/u01/bigdata/02d_d2vModel1/features/SIM_D2V300' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
#All Similarity based prediction models (Based on BOW vectors)
screen -dmS eval.appd2vTrainBOW10000.SIM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_SIMILARITYMODEL.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW10000.SIM.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/SIM_BOW10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appd2vTrainBOW5000.SIM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_SIMILARITYMODEL.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW5000.SIM.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/SIM_BOW5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
#All Similarity based prediction models (Based on TFIDF vectors)
screen -dmS eval.appD2vTrainTfidf10000.SIM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_SIMILARITYMODEL.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf10000.SIM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/SIM_TFIDF10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainTfidf5000.SIM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_SIMILARITYMODEL.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf5000.SIM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/SIM_TFIDF5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
#All Machine Learning based prediction models (Based on W2V features)
screen -dmS eval.appD2vTrainW2v100min1.SVM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min1.SVM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min1Preproc.features' 'svm' '' '/u01/bigdata/02d_d2vModel1/features/SVM_W2V100min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min1.SVM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min1.SVM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min1Preproc.features' 'svm' '' '/u01/bigdata/02d_d2vModel1/features/SVM_W2V300min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v100min2.SVM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min2.SVM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min2Preproc.features' 'svm' '' '/u01/bigdata/02d_d2vModel1/features/SVM_W2V100min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min2.SVM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min2.SVM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min2Preproc.features' 'svm' '' '/u01/bigdata/02d_d2vModel1/features/SVM_W2V300min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"

screen -dmS eval.appD2vTrainW2v100min1.LOG bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min1.LOG.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min1Preproc.features' 'log' '' '/u01/bigdata/02d_d2vModel1/features/LOG_W2V100min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
screen -dmS eval.appD2vTrainW2v100min1.XGB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min1.XGB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min1Preproc.features' 'xgb' '' '/u01/bigdata/02d_d2vModel1/features/XGB_W2V100min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min1.XGB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min1.XGB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min1Preproc.features' 'xgb' '' '/u01/bigdata/02d_d2vModel1/features/XGB_W2V300min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v100min2.XGB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min2.XGB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min2Preproc.features' 'xgb' '' '/u01/bigdata/02d_d2vModel1/features/XGB_W2V100min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min2.XGB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min2.XGB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min2Preproc.features' 'xgb' '' '/u01/bigdata/02d_d2vModel1/features/XGB_W2V300min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
screen -dmS eval.appD2vTrainW2v100min1.SEQ bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min1.SEQ.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min1Preproc.features' 'seq' '' '/u01/bigdata/02d_d2vModel1/features/SEQ_W2V100min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min1.SEQ bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min1.SEQ.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min1Preproc.features' 'seq' '' '/u01/bigdata/02d_d2vModel1/features/SEQ_W2V300min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v100min2.SEQ bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min2.SEQ.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min2Preproc.features' 'seq' '' '/u01/bigdata/02d_d2vModel1/features/SEQ_W2V100min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min2.SEQ bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min2.SEQ.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min2Preproc.features' 'seq' '' '/u01/bigdata/02d_d2vModel1/features/SEQ_W2V300min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on

screen -dmS eval.appD2vTrainW2v100min1.MLP bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min1.MLP.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min1Preproc.features' 'mlp' '' '/u01/bigdata/02d_d2vModel1/features/MLP_W2V100min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min1.MLP bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min1.MLP.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min1Preproc.features' 'mlp' '' '/u01/bigdata/02d_d2vModel1/features/MLP_W2V300min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v100min2.MLP bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min2.MLP.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min2Preproc.features' 'mlp' '' '/u01/bigdata/02d_d2vModel1/features/MLP_W2V100min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min2.MLP bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min2.MLP.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min2Preproc.features' 'mlp' '' '/u01/bigdata/02d_d2vModel1/features/MLP_W2V300min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
screen -dmS eval.appD2vTrainW2v100min1.TREE bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min1.TREE.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min1Preproc.features' 'tree' '' '/u01/bigdata/02d_d2vModel1/features/TREE_W2V100min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min1.TREE bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min1.TREE.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min1Preproc.features' 'tree' '' '/u01/bigdata/02d_d2vModel1/features/TREE_W2V300min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v100min2.TREE bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min2.TREE.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min2Preproc.features' 'tree' '' '/u01/bigdata/02d_d2vModel1/features/TREE_W2V100min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min2.TREE bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min2.TREE.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min2Preproc.features' 'tree' '' '/u01/bigdata/02d_d2vModel1/features/TREE_W2V300min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
screen -dmS eval.appD2vTrainW2v100min1.NB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min1.NB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min1Preproc.features' 'nb' '' '/u01/bigdata/02d_d2vModel1/features/NB_W2V100min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min1.NB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min1.NB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min1Preproc.features' 'nb' '' '/u01/bigdata/02d_d2vModel1/features/NB_W2V300min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v100min2.NB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min2.NB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min2Preproc.features' 'nb' '' '/u01/bigdata/02d_d2vModel1/features/NB_W2V100min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min2.NB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min2.NB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min2Preproc.features' 'nb' '' '/u01/bigdata/02d_d2vModel1/features/NB_W2V300min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
screen -dmS eval.appD2vTrainW2v100min1.DUMMY bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min1.DUMMY.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min1Preproc.features' 'dummy' '' '/u01/bigdata/02d_d2vModel1/features/DUMMY_W2V100min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min1.DUMMY bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min1.DUMMY.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min1Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min1Preproc.features' 'dummy' '' '/u01/bigdata/02d_d2vModel1/features/DUMMY_W2V300min1' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v100min2.DUMMY bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v100min2.DUMMY.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v100min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v100min2Preproc.features' 'dummy' '' '/u01/bigdata/02d_d2vModel1/features/DUMMY_W2V100min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.appD2vTrainW2v300min2.DUMMY bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainW2v300min2.DUMMY.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainW2v300min2Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestW2v300min2Preproc.features' 'dummy' '' '/u01/bigdata/02d_d2vModel1/features/DUMMY_W2V300min2' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"

#All Machine Learning based prediction models (Based on D2V features)
screen -dmS eval.cvTrainD2v100.SVM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v100.SVM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v100Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v100Preproc.features' 'svm' '' '/u01/bigdata/02d_d2vModel1/features/SVM_D2V100' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainD2v300.SVM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v300.SVM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v300Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v300Preproc.features' 'svm' '' '/u01/bigdata/02d_d2vModel1/features/SVM_D2V300' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
screen -dmS eval.cvTrainD2v100.MLP bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v100.MLP.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v100Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v100Preproc.features' 'mlp' '' '/u01/bigdata/02d_d2vModel1/features/MLP_D2V100' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainD2v300.MLP bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v300.MLP.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v300Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v300Preproc.features' 'mlp' '' '/u01/bigdata/02d_d2vModel1/features/MLP_D2V300' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"

screen -dmS eval.cvTrainD2v100.XGB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v100.XGB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v100Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v100Preproc.features' 'xgb' '' '/u01/bigdata/02d_d2vModel1/features/XGB_D2V100' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainD2v300.XGB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v300.XGB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v300Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v300Preproc.features' 'xgb' '' '/u01/bigdata/02d_d2vModel1/features/XGB_D2V300' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"

screen -dmS eval.cvTrainD2v100.SEQ bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v100.SEQ.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v100Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v100Preproc.features' 'seq' '' '/u01/bigdata/02d_d2vModel1/features/SEQ_D2V100' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainD2v300.SEQ bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v300.SEQ.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v300Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v300Preproc.features' 'seq' '' '/u01/bigdata/02d_d2vModel1/features/SEQ_D2V300' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"

sleep 5
echo Moving on
screen -dmS eval.cvTrainD2v100.TREE bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v100.TREE.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v100Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v100Preproc.features' 'tree' '' '/u01/bigdata/02d_d2vModel1/features/TREE_D2V100' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainD2v300.TREE bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v300.TREE.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v300Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v300Preproc.features' 'tree' '' '/u01/bigdata/02d_d2vModel1/features/TREE_D2V300' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
screen -dmS eval.cvTrainD2v100.NB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v100.NB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v100Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v100Preproc.features' 'nb' '' '/u01/bigdata/02d_d2vModel1/features/NB_D2V100' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainD2v300.NB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v300.NB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v300Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v300Preproc.features' 'nb' '' '/u01/bigdata/02d_d2vModel1/features/NB_D2V300' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
screen -dmS eval.cvTrainD2v100.DUMMY bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v100.DUMMY.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v100Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v100Preproc.features' 'dummy' '' '/u01/bigdata/02d_d2vModel1/features/DUMMY_D2V100' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainD2v300.DUMMY bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainD2v300.DUMMY.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainD2v300Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestD2v300Preproc.features' 'dummy' '' '/u01/bigdata/02d_d2vModel1/features/DUMMY_D2V300' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"

#All Machine Learning based prediction models (Based on BOW features)
screen -dmS eval.cvTrainBOW10000.SVM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW10000.SVM.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW10000Preproc.features' 'svm' '' '/u01/bigdata/02d_d2vModel1/features/SVM_BOW10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainBOW5000.SVM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW5000.SVM.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW5000Preproc.features' 'svm' '' '/u01/bigdata/02d_d2vModel1/features/SVM_BOW5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainBOW10000.MLP bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW10000.MLP.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW10000Preproc.features' 'mlp' '' '/u01/bigdata/02d_d2vModel1/features/MLP_BOW10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainBOW5000.MLP bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW5000.MLP.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW5000Preproc.features' 'mlp' '' '/u01/bigdata/02d_d2vModel1/features/MLP_BOW5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
screen -dmS eval.cvTrainBOW10000.XGB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW10000.XGB.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW10000Preproc.features' 'xgb' '' '/u01/bigdata/02d_d2vModel1/features/XGB_BOW10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainBOW5000.XGB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW5000.XGB.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW5000Preproc.features' 'xgb' '' '/u01/bigdata/02d_d2vModel1/features/XGB_BOW5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainBOW10000.SEQ bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW10000.SEQ.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW10000Preproc.features' 'seq' '' '/u01/bigdata/02d_d2vModel1/features/SEQ_BOW10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainBOW5000.SEQ bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW5000.SEQ.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW5000Preproc.features' 'seq' '' '/u01/bigdata/02d_d2vModel1/features/SEQ_BOW5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"


screen -dmS eval.cvTrainBOW10000.TREE bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW10000.TREE.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW10000Preproc.features' 'tree' '' '/u01/bigdata/02d_d2vModel1/features/TREE_BOW10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainBOW5000.TREE bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW5000.TREE.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW5000Preproc.features' 'tree' '' '/u01/bigdata/02d_d2vModel1/features/TREE_BOW5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainBOW10000.NB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW10000.NB.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW10000Preproc.features' 'nb' '' '/u01/bigdata/02d_d2vModel1/features/NB_BOW10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainBOW5000.NB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW5000.NB.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW5000Preproc.features' 'nb' '' '/u01/bigdata/02d_d2vModel1/features/NB_BOW5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
screen -dmS eval.cvTrainBOW10000.DUMMY bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW10000.DUMMY.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW10000Preproc.features' 'dummy' '' '/u01/bigdata/02d_d2vModel1/features/DUMMY_BOW10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainBOW5000.DUMMY bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainBOW5000.DUMMY.eval' '/u01/bigdata/02d_d2vModel1/features/appd2vTrainBOW5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestBOW5000Preproc.features' 'dummy' '' '/u01/bigdata/02d_d2vModel1/features/DUMMY_BOW5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"

echo Moving on
#All Machine Learning based prediction models (Based on TFIDF features)
screen -dmS eval.cvTrainTfidf10000.SVM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf10000.SVM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf10000Preproc.features' 'svm' '' '/u01/bigdata/02d_d2vModel1/features/SVM_TFIDF10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainTfidf5000.SVM bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf5000.SVM.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf5000Preproc.features' 'svm' '' '/u01/bigdata/02d_d2vModel1/features/SVM_TFIDF5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainTfidf10000.MLP bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf10000.MLP.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf10000Preproc.features' 'mlp' '' '/u01/bigdata/02d_d2vModel1/features/MLP_TFIDF10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainTfidf5000.MLP bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf5000.MLP.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf5000Preproc.features' 'mlp' '' '/u01/bigdata/02d_d2vModel1/features/MLP_TFIDF5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on
screen -dmS eval.cvTrainTfidf10000.XGB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf10000.XGB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf10000Preproc.features' 'xgb' '' '/u01/bigdata/02d_d2vModel1/features/XGB_TFIDF10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainTfidf5000.XGB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf5000.XGB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf5000Preproc.features' 'xgb' '' '/u01/bigdata/02d_d2vModel1/features/XGB_TFIDF5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainTfidf10000.SEQ bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf10000.SEQ.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf10000Preproc.features' 'seq' '' '/u01/bigdata/02d_d2vModel1/features/SEQ_TFIDF10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainTfidf5000.SEQ bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf5000.SEQ.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf5000Preproc.features' 'seq' '' '/u01/bigdata/02d_d2vModel1/features/SEQ_TFIDF5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
sleep 5
echo Moving on

screen -dmS eval.cvTrainTfidf10000.TREE bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf10000.TREE.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf10000Preproc.features' 'tree' '' '/u01/bigdata/02d_d2vModel1/features/TREE_TFIDF10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainTfidf5000.TREE bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf5000.TREE.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf5000Preproc.features' 'tree' '' '/u01/bigdata/02d_d2vModel1/features/TREE_TFIDF5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainTfidf10000.NB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf10000.NB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf10000Preproc.features' 'nb' '' '/u01/bigdata/02d_d2vModel1/features/NB_TFIDF10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainTfidf5000.NB bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf5000.NB.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf5000Preproc.features' 'nb' '' '/u01/bigdata/02d_d2vModel1/features/NB_TFIDF5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainTfidf10000.DUMMY bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf10000.DUMMY.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf10000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf10000Preproc.features' 'dummy' '' '/u01/bigdata/02d_d2vModel1/features/DUMMY_TFIDF10000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"
screen -dmS eval.cvTrainTfidf5000.DUMMY bash -c "python3 /home/kah1/remote_cookie_runtime/src/pipes/ModelPhase_MLCLASSIFIER.py '/u01/bigdata/02d_d2vModel1/features/eval_cvTrainTfidf5000.DUMMY.eval' '/u01/bigdata/02d_d2vModel1/features/appD2vTrainTfidf5000Preproc.features' '/u01/bigdata/02d_d2vModel1/features/cvTestTfidf5000Preproc.features' 'dummy' '' '/u01/bigdata/02d_d2vModel1/features/DUMMY_TFIDF5000' 'removeStopwords,toLowercase,replaceSlash,flatEmail,flatMonth,flatNumber,lemmatize' education,skill:language,personal,experience '0,1,2,3' '/u01/bigdata/00_appjson';exec sh"


echo run this only after all the python processes are completed. (type 'top' to view processes)
echo python3 /home/kah1/remote_cookie_runtime/src/pipes/EVALSummaryPhase_GENERATE.py '/u01/bigdata/02d_d2vModel1/featureset3NoPreproc/features/summary_.eval' '/u01/bigdata/02d_d2vModel1/featureset3NoPreproc/features'
